---
title: "bayes_musings"
author: "Merritt Aho"
date: "12/23/2021"
output: html_document
---

```{r setup, include=FALSE}
library(rstanarm)
library(bayestestR)
library(dplyr)
library(tidyr)
library(insight)
library(ggplot2)
library(see)

```



```{r test_data}

# Historical conversion data
prior_traffic <- 2000
prior_cvr <- .1
prior_se <- sqrt(prior_cvr*(1 - prior_cvr)/prior_traffic)
  
# Test Analysis
traffic_a <- 100000
traffic_b <- traffic_a
# conversions_a <- traffic_a * .1
# conversions_b <- conversions_a * 1.1
cvr_a <- .04
cvr_b <- cvr_a * 1.1

test_data <- data.frame(recipe = c("A","B"), cvr = c(cvr_a, cvr_b), traffic = c(traffic_a, traffic_b))
  
  # all_test_data <- data.frame(recipe = c(rep("A",traffic_a), rep("B",traffic_b)), conversion = c(rep(0,traffic_a - conversions_a),rep(1,conversions_a),rep(0,traffic_b - conversions_b),rep(1,conversions_b)))
  # 
  # all_test_data %>% 
  #   group_by(recipe) %>% 
  #   summarise(conversion_rate = sum(conversion)/n())
  
  test_data

```


```{r bayes_model, echo=FALSE}
model <- stan_glm(cvr ~ recipe, data = test_data, weights = traffic, family = "binomial",
                  prior = normal(0,.1), # prior of the effect size (main parameter in the posterior)
                  # setting prior SD to < 1 narrows the prior distribution
                  # prior_intercept = normal(prior_cvr,prior_se), # prior of the control variant..this isn't right
                  chains = 2, iter = 1000, warmup = 250)

posteriors <- insight::get_parameters(model)

head(posteriors)

```



```{r bayes_analysis, echo=FALSE}

ggplot(posteriors, aes(x = recipeB)) +
  geom_density(fill = "orange") +
  # The mean in blue
  geom_vline(xintercept = mean(posteriors$recipeB), color = "blue", size = 1) +
  # The median in red
  geom_vline(xintercept = median(posteriors$recipeB), color = "red", size = 1) +
  # The MAP in purple
  geom_vline(xintercept = map_estimate(posteriors$recipeB), color = "purple", size = 1)

hdi(posteriors$recipeB, ci = .9)

plot(rope(posteriors$recipeB, range = c(-0.01,0.01), ci = .9))

pd <- p_direction(posteriors$recipeB)
plot(pd)
```
```{r}
describe_posterior(model, test = c("p_direction", "rope", "bayesfactor"))
```

```{r echo=FALSE}
# https://easystats.github.io/bayestestR/articles/bayes_factors.html
bf <- bayesfactor_parameters(model, null = c(-.01, .01))

plot(bf)
```

```{r individual_posteriors}

# Function to convert logodds to prob https://sebastiansauer.github.io/convert_logit2prob/
logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}

## Plot the posterior distributions of each group
recipe_posteriors <- posteriors %>%
  mutate(A = logit2prob(`(Intercept)`),
         B = logit2prob(`(Intercept)` + recipeB)) %>%
  subset(select = c(A,B)) %>% 
  pivot_longer(cols = c(A,B))

 
ggplot(data = recipe_posteriors, aes(x = value, fill = name)) +
  geom_density(alpha = 0.5)

```



```{r bayesAB_demo}
library(bayesAB)

A_binom <- rbinom(250, 1, .25)
B_binom <- rbinom(250, 1, .2)

AB1 <- bayesTest(A_binom, B_binom, priors = c('alpha' = 65, 'beta' = 200), n_samples = 1e5, distribution = 'bernoulli')

# You can get the posterior with AB1$posteriors$Probability$A or AB1$posteriors$Probability$B
# 3 Plot types: priors, posteriors (a & b params), samples (effect size)
```

